require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/utterances", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Utterance. As you add validations to Utterance, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Utterance.create! valid_attributes
      get utterances_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      utterance = Utterance.create! valid_attributes
      get utterance_url(utterance)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_utterance_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      utterance = Utterance.create! valid_attributes
      get edit_utterance_url(utterance)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Utterance" do
        expect {
          post utterances_url, params: {utterance: valid_attributes}
        }.to change(Utterance, :count).by(1)
      end

      it "redirects to the created utterance" do
        post utterances_url, params: {utterance: valid_attributes}
        expect(response).to redirect_to(utterance_url(Utterance.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Utterance" do
        expect {
          post utterances_url, params: {utterance: invalid_attributes}
        }.to change(Utterance, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post utterances_url, params: {utterance: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested utterance" do
        utterance = Utterance.create! valid_attributes
        patch utterance_url(utterance), params: {utterance: new_attributes}
        utterance.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the utterance" do
        utterance = Utterance.create! valid_attributes
        patch utterance_url(utterance), params: {utterance: new_attributes}
        utterance.reload
        expect(response).to redirect_to(utterance_url(utterance))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        utterance = Utterance.create! valid_attributes
        patch utterance_url(utterance), params: {utterance: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested utterance" do
      utterance = Utterance.create! valid_attributes
      expect {
        delete utterance_url(utterance)
      }.to change(Utterance, :count).by(-1)
    end

    it "redirects to the utterances list" do
      utterance = Utterance.create! valid_attributes
      delete utterance_url(utterance)
      expect(response).to redirect_to(utterances_url)
    end
  end
end
