# Name of your application. Used to uniquely configure containers.
service: mattkelly_io

# Name of the container image.
image: your-user/mattkelly_io

# Deploy to these servers.
servers:
  web:
    - 192.168.0.1

# Enable SSL auto certification via Let's Encrypt
proxy:
  ssl: true
  host: app.example.com

# Credentials for your image host.
registry:
  username: your-user
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    # Set number of cores available to the application on each server (default: 1).
    WEB_CONCURRENCY: 2

# Aliases for common commands
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f

# Use a persistent storage volume for uploaded files
volumes:
  - "mattkelly_io_storage:/rails/storage"

# Bridge fingerprinted assets between versions
asset_path: /rails/public/assets

# Configure the image builder
builder:
  arch: amd64
